#!/usr/bin/env python3
"""Write the Git-derived build label consumed by the GBA front end."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def git_text(project_root: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(project_root), *arguments],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
    )
    return result.stdout.strip()


def tracked_tree_is_dirty(project_root: Path) -> bool:
    for arguments in (
        ("diff", "--quiet", "--"),
        ("diff", "--cached", "--quiet", "--"),
    ):
        result = subprocess.run(
            ["git", "-C", str(project_root), *arguments],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode == 1:
            return True
        if result.returncode != 0:
            raise RuntimeError(
                f"git {' '.join(arguments)} failed with {result.returncode}"
            )
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()

    project_root = arguments.project_root.resolve()
    short_hash = git_text(project_root, "rev-parse", "--short=7", "HEAD")
    dirty_suffix = "+" if tracked_tree_is_dirty(project_root) else ""
    display_hash = short_hash + dirty_suffix
    content = (
        "/* Generated by tools/write_build_version.py; do not edit. */\n"
        "#ifndef TYRIAN_GBA_BUILD_VERSION_H\n"
        "#define TYRIAN_GBA_BUILD_VERSION_H\n"
        f'#define TYRIAN_GBA_BUILD_GIT_HASH "{display_hash}"\n'
        f'#define TYRIAN_GBA_BUILD_LABEL "AprTyrianGba-{display_hash}"\n'
        "#endif\n"
    )

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if (
        arguments.output.exists()
        and arguments.output.read_text(encoding="utf-8") == content
    ):
        return 0
    arguments.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
