#!/usr/bin/env python3
"""Write the Git-derived build label consumed by the GBA front end."""

from __future__ import annotations

import argparse
import subprocess
from datetime import date
from pathlib import Path


def git_text(project_root: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(project_root), *arguments],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
    )
    return result.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()

    project_root = arguments.project_root.resolve()
    short_hash = git_text(project_root, "rev-parse", "--short=7", "HEAD")
    build_date = date.today().strftime("%Y%m%d")
    # Keep the public in-ROM identifier stable and copy-friendly.  A local
    # dirty marker made normal developer builds display a confusing trailing
    # '+', while the actual source state is already available from Git.  The
    # local build date makes otherwise identical rebuilds easy to distinguish.
    display_hash = short_hash
    content = (
        "/* Generated by tools/write_build_version.py; do not edit. */\n"
        "#ifndef TYRIAN_GBA_BUILD_VERSION_H\n"
        "#define TYRIAN_GBA_BUILD_VERSION_H\n"
        f'#define TYRIAN_GBA_BUILD_GIT_HASH "{display_hash}"\n'
        f'#define TYRIAN_GBA_BUILD_DATE "{build_date}"\n'
        f'#define TYRIAN_GBA_BUILD_LABEL '
        f'"AprTyrianGba-{display_hash}-{build_date}"\n'
        "#endif\n"
    )

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if (
        arguments.output.exists()
        and arguments.output.read_text(encoding="utf-8") == content
    ):
        return 0
    arguments.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
